tax: 8.0
cash_on_delivery:
  - [     0,  300]
  - [ 10000,  400]
  - [ 30000,  600]
  - [100000, 1000]
postage:
  price: 600
  amount: 5
delivery_timezone:
  - "8時-12時"
  - "12時-14時"
  - "14時-16時"
  - "16時-18時"
  - "18時-20時"
  - "20時-21時"